feat(script): refund bot
WavesHQ/walletkit pull request #109
Opened 2023-03-16 08:55 UTC by chloezxyy

#### What this PR does / why we need it:
- Created a `walletkit-bot` package for running scripts in Quantum bridge
- In the DFC -> EVM flow, this script is to refund users who requests a refund to get their tokens back from the bridge's hot wallet to their specified DeFiChain refund address

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:
- In the event where user sends DFI tokens instead of UTXO, script will not be handling that scenario 
- We need to top up the hot wallet with DFI UTXO manually in the hot wallet for the refund to go through

2023-03-20 08:42 UTC, pierregee requested changes

2023-03-20 08:42 UTC, pierregee commented on packages/walletkit-bot/src/api/RefundBot.ts
> +  const tokenId = (await account.client.tokens.list()).find(
tokenSymbol is a string. If the symbol is not found, log the error and `return` bec It should not go through the tx if the tokenId is not found

2023-03-20 08:42 UTC, pierregee commented on packages/walletkit-bot/src/api/RefundBot.ts
> +    claimAmount,
let's add validation that it's greater than 0 and a valid number

2023-03-20 08:42 UTC, pierregee commented on packages/walletkit-bot/src/api/RefundBot.ts
> +    refundAddress,
let's add validation that it is a valid dfc address

2023-03-20 08:42 UTC, pierregee commented on packages/walletkit-bot/src/api/RefundBot.ts
> +    index,
add validation that it's a positive number

2023-03-20 09:09 UTC, chloezxyy commented on packages/walletkit-bot/src/api/RefundBot.ts
> +    refundAddress,
Validation is being done in getAddressScript()

2023-03-21 03:40 UTC, pierregee requested changes

2023-03-21 03:40 UTC, pierregee commented on packages/walletkit-bot/src/api/RefundBot.ts
> +  const txn: TransactionSegWit = await builder.account.accountToAccount(
As per the [ticket](https://github.com/BirthdayResearch/quantum/issues/761), quantum will have UTXO <-> ERC20-DFI
So if the tokenSymbol is DFI, we need to use `await builder.utxo.send` to send DFI UTXO instead of DFI token

2023-03-21 06:43 UTC, chloezxyy commented on packages/walletkit-bot/src/api/RefundBot.ts
> +  const txn: TransactionSegWit = await builder.account.accountToAccount(
Since it is assumed that `tokenSymbol === 'DFI'` in UTXO from the DB, `account.client.tokens.list()` will just check for the related token id that is tagged under DFI

2023-03-22 02:47 UTC, pierregee requested changes

2023-03-22 02:47 UTC, pierregee commented on packages/walletkit-bot/src/api/RefundBot.ts
> +    console.log(error);
```suggestion
    console.log((error as Error).message);
```
I think we don't need to log the whole error object

2023-03-22 02:47 UTC, pierregee commented on packages/walletkit-bot/src/api/RefundBot.ts
> +    if (new BigNumber(claimAmount).isLessThanOrEqualTo(0)) {
`  claimAmount: '1sss',` is not handled , can add checks if isNaN

2023-03-22 02:50 UTC, pierregee commented on packages/walletkit-bot/src/api/RefundBot.ts
> +    if (isDFI) {
can't we just use the tokenSymbol instead of hardcoding tokenId? 
`tokenSymbol === "DFI"`

2023-03-22 05:01 UTC, chloezxyy commented on packages/walletkit-bot/src/api/RefundBot.ts
> +    if (isDFI) {
we can~~

2023-03-22 06:53 UTC, thedoublejay approved these changes

2023-03-22 06:54 UTC, thedoublejay approved these changes

2023-03-22 06:54 UTC, merged