chore(core): add eth address validator
WavesHQ/walletkit pull request #137
Opened 2023-05-10 05:03 UTC by JoshuaC817

#### What this PR does / why we need it:
Validate eth address using ethers package

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

2023-05-18 05:03 UTC, fullstackninja864 requested changes

2023-05-19 01:59 UTC, pierregee commented on packages/walletkit-core/src/api/addressValidator.ts
> +export const validateEthAddress = (address: string): boolean =>
No use case for it on DeFiScan, we can remove

2023-05-19 02:11 UTC, pierregee requested changes

2023-05-19 02:11 UTC, pierregee commented on packages/walletkit-core/src/api/addressValidator.unit.ts
> +
Once `validateEthAddress`, let's move these tests on `getDecodedAddress`

2023-05-19 05:05 UTC, JoshuaC817 commented on packages/walletkit-core/src/api/addressValidator.ts
> +export const validateEthAddress = (address: string): boolean =>
Done removed

2023-05-19 05:06 UTC, JoshuaC817 commented on packages/walletkit-core/src/api/addressValidator.unit.ts
> +
currently PushData in Script would only accept hex, so the addresses above could not be used in the test cases

2023-05-24 07:27 UTC, fullstackninja864 commented
Do we need to export `getDecodedAddress` in `packages/walletkit-core/src/api/index.ts` ?

2023-05-24 09:26 UTC, fullstackninja864 approved these changes

2023-05-25 03:45 UTC, merged